### ISSUE TITLE
Predictive model creation (logistic regression)

### ISSUE THREAD

**Issue by noahbjohnson** [noahbjohnson/DS420#5]
Full model

**Comment by noahbjohnson** [comment]
@tshaffer54 in d03d84881e68c9e50ada75a1d857321d0eadb0f4 `x, y` are not defined in the third cell.

**Comment by tshaffer54** [comment]
im an idiot and dont remember the website, wanna send it to me

**Comment by tshaffer54** [comment]
I believe i fixed the x, y definition

**Comment by noahbjohnson** [comment]
Looks good, closing it out.
